import Controller.ParkingController;
import Controller.Router;
import Model.ParkingBoy;
import Model.ParkingLot;
import View.CLI;
import View.Request;
import View.Response;

import java.util.LinkedList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
	    List<ParkingLot> parkingLots = new LinkedList<>();
		parkingLots.add(new ParkingLot(1,"西南停车场",1));
	    ParkingBoy parkingBoy = new ParkingBoy(parkingLots);

	    ParkingController parkingController = new ParkingController(parkingBoy);

		Request request = new Request();
	    Response response = new Response();

	    CLI cli = new CLI();
		Router router = new Router(parkingController);
		router.getIndexView(response);

		while (true){
			String command = cli.input();
			request.setParameter(command);
			router.handleRequest(request,response);
		}
    }
}
