import Controller.ParkingController;
import Model.ParkingBoy;
import Model.ParkingLot;
import View.CLI;
import View.Request;
import View.Response;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
	    ParkingLot parkingLot = new ParkingLot(1);
	    List<ParkingLot> parkingLots = new LinkedList<>();
	    parkingLots.add(parkingLot);

	    ParkingBoy parkingBoy = new ParkingBoy(parkingLots);

	    ParkingController parkingController = new ParkingController(parkingBoy);

		Request request = new Request();

	    CLI cli = new CLI();
		Router router = new Router(parkingController);
		router.getIndexView();

		while (true){
			String command = cli.input();
			request.setParameter(command);
			router.handleRequest(request);
		}
    }
}
